### ISSUE TITLE
Upgrade to maintained version of zxcvbn

### ISSUE THREAD

**Issue by covert-encryption** [covert-encryption/covert-web#2]
Should use an actively maintained fork because Dropbox abandoned their open source development five years ago.

This one seems best: https://github.com/zxcvbn-ts/zxcvbn

**Comment by sh-dv** [comment]
Done. 
However, this package has different cracking time estimation. : 
```
{
    onlineThrottling100PerHour,
    onlineNoThrottling10PerSecond,
    offlineSlowHashing1e4PerSecond,
    offlineFastHashing1e10PerSecond
}
```

I chose to use the last one. 

example when estimating the crack time for "quitelegitlongpwd" : 
```

{
    onlineThrottling100PerHour: 'centuries',
    onlineNoThrottling10PerSecond: 'centuries',
    offlineSlowHashing1e4PerSecond: '14 years',
    offlineFastHashing1e10PerSecond: '8 minutes'
}
```

**Comment by sh-dv** [comment]
zxcvbn-ts shows lesser crack time estimation when using the built in `zxcvbn(pwd).crackTimesDisplay.offlineFastHashing1e10PerSecond` compared to the `TimeEstimates.displayTime((.7/100 * guesses)*costfactor(encode(pwd))`

That's why i switched to default estimation.

**Comment by covert-encryption** [comment]
Covert does custom calculation because we use stronger password hashing than anyone else, in particular for the short passwords (that the costfactor adjusts for). Are you saying that zxcvbn-ts does not offer the number or guesses (needed for that calculation) or that it has no pretty output formatting function like `TimeEstimates.displaytime`?

Of the built-in options, `onlineNoThrottling10PerSecond` would be closest to reality and can be used at least until the proper calculation can be implemented.

**Comment by sh-dv** [comment]
solved
